# Generated by Django 5.0.2 on 2024-02-16 00:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartmint_chalit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apa_cha_status', models.BooleanField(verbose_name='الحاله')),
            ],
            options={
                'verbose_name': 'شقه او شاليه',
                'verbose_name_plural': 'الشقق والشاليهات',
            },
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('apartmint_chalit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.apartmint_chalit')),
                ('apa_name', models.CharField(max_length=20, verbose_name='اسم الشقه')),
                ('apa_floor', models.CharField(max_length=20, null=True, verbose_name='الطابق')),
                ('apa_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('apa_discrip', models.TextField(max_length=50, null=True, verbose_name='الوصف')),
                ('apa_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شقه',
                'verbose_name_plural': 'الشقق',
            },
            bases=('system.apartmint_chalit',),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bra_name', models.CharField(max_length=20, verbose_name='اسم الفرع')),
                ('bra_address', models.CharField(max_length=20, verbose_name='عنوان الفرع')),
                ('bra_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name=' المستخدم')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bun_name', models.CharField(max_length=50, verbose_name='اسم الباقه')),
                ('bun_people_number', models.IntegerField(null=True, verbose_name='عدد الأشخاص')),
                ('bun_entrytime', models.TimeField(null=True, verbose_name='وقت الدخول')),
                ('bun_exittime', models.TimeField(null=True, verbose_name='وقت الخروج')),
                ('bun_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('addpeo_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الاأشخاص الأضافيين')),
                ('bun_childprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الأطفال')),
                ('bun_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'باقه',
                'verbose_name_plural': 'الباقات',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('che_status', models.BooleanField(verbose_name='الحاله')),
                ('che_date', models.DateField(verbose_name='التاريخ')),
                ('che_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'فحص',
                'verbose_name_plural': 'الفحص',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=50, verbose_name='المحتوى')),
                ('con_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('con_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('ap_chalit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.apartmint_chalit', verbose_name='الشقق والشاليهات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'المحتوى',
                'verbose_name_plural': 'المحتويات',
            },
        ),
        migrations.CreateModel(
            name='Checkdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_status', models.BooleanField(verbose_name='حاله المحتوى')),
                ('check1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.check', verbose_name='الفحص')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.content', verbose_name='المحتوى')),
            ],
            options={
                'verbose_name': 'تفاصيل',
                'verbose_name_plural': 'تفاصيل الجرد',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50, verbose_name='اسم العميل')),
                ('cus_card_id', models.IntegerField(verbose_name='رقم البطاقه')),
                ('cus_phone_number', models.IntegerField(verbose_name='رقم التلفون')),
                ('cus_address', models.CharField(max_length=20, null=True, verbose_name='العنوان')),
                ('cus_age', models.IntegerField(null=True, verbose_name='العمر')),
                ('cus_gender', models.CharField(max_length=10, null=True, verbose_name='الجنس')),
                ('cus_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_name', models.CharField(max_length=30, verbose_name='اسم الصندوق')),
                ('fun_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'الصندوق',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mor_date', models.DateField(null=True, verbose_name='التاريخ')),
                ('mor_type', models.CharField(max_length=50, verbose_name='نوع الرهن')),
                ('mor_notice', models.TextField(null=True, verbose_name='ملاحظات')),
                ('mor_amaunt', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ')),
                ('mor_status', models.BooleanField(verbose_name='الحاله')),
                ('mor_add_datetme', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.fund', verbose_name='الصندوق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رهن',
                'verbose_name_plural': 'الرهونات',
            },
        ),
        migrations.CreateModel(
            name='Reserveape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateField(null=True, verbose_name='تاريخ الحجز')),
                ('login_datetime', models.DateTimeField(verbose_name='تاريخ ووقت الدخول')),
                ('exit_datetime', models.DateTimeField(verbose_name='تاريخ ووقت الخروج')),
                ('res_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('add_datetme', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.apartments', verbose_name='الشقه')),
            ],
            options={
                'verbose_name': 'حجز ',
                'verbose_name_plural': 'حجز شقه',
            },
        ),
        migrations.CreateModel(
            name='Reservecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_cha_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('login_datetime', models.DateTimeField(verbose_name='تاريخ ووقت الدخول')),
                ('exit_datetime', models.DateTimeField(verbose_name='تاريخ ووقت الخروج')),
                ('res_cha_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('bunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bunch', verbose_name='نوع الباقه')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز ',
                'verbose_name_plural': 'حجز شاليه',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peo_name', models.CharField(max_length=50, verbose_name='الأسم')),
                ('peo_age', models.IntegerField(verbose_name='العمر')),
                ('peo_card_number', models.IntegerField(null=True, verbose_name='رقم البطاقه')),
                ('peo_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('reservecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.reservecha', verbose_name='اسم الحجز')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_notice', models.TextField(null=True, verbose_name='ملاحظات')),
                ('pay_amountoutside', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المنصرف')),
                ('pay_amountinside', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ الوارد')),
                ('pay_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='التاريخ والوقت')),
                ('add_datetme', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.fund', verbose_name='الصندوق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('reserveape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.reserveape', verbose_name='الشاليه')),
                ('reservecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.reservecha', verbose_name='الشقه')),
            ],
            options={
                'verbose_name': 'عمليه',
                'verbose_name_plural': 'العمليات',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='reservecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.reservecha', verbose_name='اسم الحجز'),
        ),
        migrations.CreateModel(
            name='Towers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tow_name', models.CharField(max_length=20, verbose_name='اسم البرج')),
                ('tow_floornumber', models.IntegerField(verbose_name='عدد الطوابق')),
                ('tow_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' المستخدم')),
            ],
            options={
                'verbose_name': 'برج',
                'verbose_name_plural': 'البرج',
            },
        ),
        migrations.AddField(
            model_name='apartmint_chalit',
            name='towers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.towers', verbose_name='البرج'),
        ),
        migrations.CreateModel(
            name='Chalets',
            fields=[
                ('apartmint_chalit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.apartmint_chalit')),
                ('cha_name', models.CharField(max_length=20, verbose_name='اسم الشاليه')),
                ('cha_floor', models.CharField(max_length=20, null=True, verbose_name='الطابق')),
                ('cha_discrip', models.TextField(max_length=50, null=True, verbose_name='الوصف')),
                ('cha_add_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ ووقت الأضافه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شاليه',
                'verbose_name_plural': 'الشاليهات',
            },
            bases=('system.apartmint_chalit',),
        ),
        migrations.AddField(
            model_name='bunch',
            name='chalits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.chalets', verbose_name='الشاليه'),
        ),
    ]
