# Generated by Django 4.2.5 on 2024-03-17 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunch',
            name='chalits',
        ),
        migrations.AddField(
            model_name='reservecha',
            name='chalits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.chalets', verbose_name='الشاليه'),
        ),
        migrations.AlterField(
            model_name='reserveape',
            name='apartments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.apartments', verbose_name='الشقه'),
        ),
        migrations.AlterField(
            model_name='reserveape',
            name='customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل'),
        ),
    ]
