# Generated by Django 4.2.5 on 2024-03-18 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_bunch_chalits_reservecha_chalits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservecha',
            name='chalits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.chalets', verbose_name='الشاليه'),
        ),
    ]
