# Generated by Django 4.2.5 on 2024-03-18 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_reservecha_chalits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservecha',
            name='res_cha_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الحجز'),
        ),
    ]
