# Generated by Django 4.2.5 on 2024-03-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_reservecha_res_cha_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservecha',
            name='exit_datetime',
            field=models.TimeField(verbose_name='تاريخ ووقت الخروج'),
        ),
        migrations.AlterField(
            model_name='reservecha',
            name='login_datetime',
            field=models.TimeField(verbose_name='تاريخ ووقت الدخول'),
        ),
    ]
