# Generated by Django 4.2.5 on 2024-03-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_reservecha_exit_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservecha',
            old_name='exit_datetime',
            new_name='exit_time',
        ),
        migrations.RenameField(
            model_name='reservecha',
            old_name='login_datetime',
            new_name='login_time',
        ),
    ]
