# Generated by Django 4.2.5 on 2024-03-23 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0006_rename_exit_datetime_reservecha_exit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservecha',
            name='exit_time',
            field=models.TimeField(verbose_name='وقت الخروج'),
        ),
        migrations.AlterField(
            model_name='reservecha',
            name='login_time',
            field=models.TimeField(verbose_name='وقت الدخول'),
        ),
        migrations.AlterField(
            model_name='reservecha',
            name='user',
            field=models.ForeignKey(default='abdalrahman', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
