# Generated by Django 4.2.5 on 2024-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_reservecha_exit_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveape',
            name='exit_datetime',
        ),
        migrations.RemoveField(
            model_name='reserveape',
            name='login_datetime',
        ),
        migrations.RemoveField(
            model_name='reserveape',
            name='res_date',
        ),
        migrations.AddField(
            model_name='reserveape',
            name='exit_date',
            field=models.DateField(null=True, verbose_name='تاريخ الخروج'),
        ),
        migrations.AddField(
            model_name='reserveape',
            name='login_date',
            field=models.DateField(null=True, verbose_name='تاريخ الدخول'),
        ),
        migrations.AddField(
            model_name='reserveape',
            name='res_notice',
            field=models.TextField(null=True, verbose_name='ملاحظات'),
        ),
    ]
