# Generated by Django 4.2.5 on 2024-03-28 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0008_remove_reserveape_exit_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservecha',
            name='st_book',
            field=models.BooleanField(null=True, verbose_name='الحاله'),
        ),
        migrations.AlterField(
            model_name='people',
            name='user',
            field=models.ForeignKey(default='abdalrahman', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='reserveape',
            name='user',
            field=models.ForeignKey(default='abdalrahman', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
