# Generated by Django 4.2.5 on 2024-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_reservecha_st_book_alter_people_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveape',
            name='st_book',
            field=models.BooleanField(null=True, verbose_name='الحاله'),
        ),
    ]
