# Generated by Django 4.2.5 on 2024-03-31 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_reserveape_st_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resapa_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateField(null=True, verbose_name='التواريخ المحجوزه')),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.apartments', verbose_name='الشقه')),
                ('reserveape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.reserveape', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'تاريخ ',
                'verbose_name_plural': 'التواريخ المحجوزه',
            },
        ),
    ]
