# Generated by Django 4.2.5 on 2024-03-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_resapa_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resapa_date',
            name='reserveape',
        ),
    ]
