# Generated by Django 4.2.5 on 2024-04-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_remove_resapa_date_reserveape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resapa_date',
            name='res_date',
            field=models.TextField(null=True, verbose_name='التواريخ المحجوزه'),
        ),
    ]
