# Generated by Django 4.2.5 on 2024-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_resapa_date_res_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resapa_date',
            name='res_date',
            field=models.CharField(max_length=50, null=True, verbose_name='التواريخ المحجوزه'),
        ),
    ]
