# Generated by Django 4.2.5 on 2024-04-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_resapa_date_res_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmint_chalit',
            name='apa_cha_status',
            field=models.BooleanField(default=True, verbose_name='الحاله'),
        ),
    ]
