# Generated by Django 4.2.5 on 2024-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_alter_apartmint_chalit_apa_cha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='apa_status',
            field=models.BooleanField(null=True, verbose_name='الحاله'),
        ),
        migrations.AlterField(
            model_name='apartmint_chalit',
            name='apa_cha_status',
            field=models.BooleanField(null=True, verbose_name='الحاله'),
        ),
    ]
