# Generated by Django 4.2.5 on 2024-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_apartments_apa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalets',
            name='cha_status',
            field=models.BooleanField(null=True, verbose_name='الحاله'),
        ),
    ]
