# Generated by Django 4.2.5 on 2024-04-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_chalets_cha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalets',
            name='cha_status',
            field=models.BooleanField(default=True, null=True, verbose_name='الحاله'),
        ),
    ]
