# Generated by Django 4.2.5 on 2024-04-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_chalets_cha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservecha',
            name='st_book',
            field=models.CharField(choices=[('sure', 'مؤكد'), ('notsure', 'غير مؤكد'), ('cancel', 'ملغي')], max_length=20, null=True, verbose_name='الحاله'),
        ),
    ]
