# Generated by Django 4.2.5 on 2024-04-15 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_alter_reserveape_st_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='pay_datetime',
        ),
        migrations.AddField(
            model_name='operation',
            name='pay_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='reserveape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.reserveape', verbose_name='الشقه'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='reservecha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.reservecha', verbose_name='الشاليه'),
        ),
    ]
