# Generated by Django 4.2.5 on 2024-04-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_alter_operation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل'),
        ),
    ]
