# Generated by Django 4.2.5 on 2024-04-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_operation_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='pay_amountinside',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ الوارد'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='pay_amountoutside',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ المنصرف'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='reserveape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.reserveape', verbose_name='الشقه'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='reservecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.reservecha', verbose_name='الشاليه'),
        ),
    ]
