# Generated by Django 4.2.5 on 2024-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_alter_operation_pay_amountinside_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='f_or',
            field=models.TextField(null=True, verbose_name='لأجل'),
        ),
        migrations.AddField(
            model_name='operation',
            name='recipient_name',
            field=models.TextField(null=True, verbose_name='اسم المستلم'),
        ),
    ]
