# Generated by Django 4.2.5 on 2024-05-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_operation_f_or_operation_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='f_or',
            field=models.CharField(max_length=100, null=True, verbose_name='لأجل'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='recipient_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم المستلم'),
        ),
    ]
