# Generated by Django 4.2.5 on 2024-05-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_alter_operation_f_or_alter_operation_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.customers', verbose_name='اسم العميل'),
        ),
    ]
