# Generated by Django 4.2.5 on 2024-05-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_alter_reserveape_st_book_alter_reservecha_st_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_logo', models.ImageField(upload_to='', verbose_name='شعار الموسسه')),
                ('f_name_ar', models.CharField(max_length=100, verbose_name='اسم الموسسه ar')),
                ('f_name_en', models.CharField(max_length=100, verbose_name=' اسم الموسسه en')),
                ('f_address_ar', models.CharField(max_length=100, verbose_name='العنوان ar')),
                ('f_address_en', models.CharField(max_length=100, verbose_name='العنوان en')),
                ('f_phon_ar', models.IntegerField(verbose_name='الرقم')),
                ('f_phon_en', models.IntegerField(verbose_name='الرقم')),
            ],
        ),
    ]
