# Generated by Django 4.2.5 on 2024-06-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_firm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'البيانات', 'verbose_name_plural': 'الموسسه'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='ap_chalit',
        ),
        migrations.AddField(
            model_name='content',
            name='chalit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.chalets', verbose_name=' الشاليهات'),
        ),
    ]
