# Generated by Django 4.2.5 on 2024-06-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_alter_firm_options_remove_content_ap_chalit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgage',
            name='customers',
        ),
        migrations.AddField(
            model_name='mortgage',
            name='reservecha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.reservecha', verbose_name='رقم الحجز'),
        ),
    ]
