# Generated by Django 4.2.5 on 2024-06-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_remove_mortgage_customers_mortgage_reservecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='st_people',
            field=models.CharField(choices=[('enter', 'تم الدخول'), ('notenter', 'لم يتم الدخول')], default='notenter', max_length=20, null=True, verbose_name='الحاله'),
        ),
    ]
