# Generated by Django 4.2.5 on 2024-06-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_people_st_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='mor_status',
            field=models.BooleanField(null=True, verbose_name='الحاله'),
        ),
    ]
