# Generated by Django 4.2.5 on 2024-06-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_alter_mortgage_mor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='mor_status',
            field=models.BooleanField(default=False, null=True, verbose_name='الحاله'),
        ),
    ]
