# Generated by Django 4.2.5 on 2024-06-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_alter_mortgage_mor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='mor_amaunt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='المبلغ'),
        ),
    ]
