from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('index', views.index, name='index'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', views.login, name='login'),
    path('acc', views.acc, name='acc'), 
    path('acc/expenses', views.expenses, name='expenses'), 
    path('acc/income', views.income, name='income'), 
    path('cuscha', views.cuscha, name='cuscha'),
    path('cusapa', views.cusapa, name='cusapa'),
    path('acc/mortgaga', views.mortgaga, name='mortgaga'), 
    path('clint',views.client, name='client'),
    path('apdate/<int:id>', views.apdateclientdataa, name='apdateclientdataa'),
    path('<int:id>', views.st_mor, name='st_mor'),
    path('clintdata',views.clientdata, name='clientdata'),
    path('services',views.services, name='services'),
    path('done_tasks',views.done_tasks, name='done_tasks'),
    path('tasks',views.tasks, name='tasks'),
    path('contents/<int:id>',views.contents, name='contents'),
    path('apartment_book/<int:id>',views.apartment_book, name='apartment_book'),
    path('validateresapa', views.validateresapa, name='validateresapa'),
    path('chalih_book/<int:id>',views.chalih_book, name='chalih_book'),
    path('validate', views.validate, name='validate'),
    path('validaterescha', views.validaterescha, name='validaterescha'),
    path('daterescha', views.daterescha, name='daterescha'),
    path('chalih_people/<int:id>',views.chalih_people, name='chalih_people'),
    path('donebookings',views.donebookings, name='donebookings'),
    path('chalih_bookings',views.chalih_bookings, name='chalih_bookings'),
    path('apartment_bookings',views.apartment_bookings, name='apartment_bookings'),
    path('apdate_apartment_book/<int:id>',views.apdate_apartment_book, name='apdate_apartment_book'),
    path('apdate_chalih_book/<int:id>',views.apdate_chalih_book, name='apdate_chalih_book'),
    path('get_dates',views.get_dates, name='get_dates'),
    path('bill/<int:id>',views.bill, name='bill'),
    path('reports',views.reports, name='reports'),
    path('bills',views.bills, name='bills'),
    path('out/<int:id>',views.out, name='out'),
    path('report',views.report, name='report'),
    path('acc_records',views.acc_records, name='acc_records'),
    path('customer_record',views.customer_record, name='customer_record'),
    path('rent_records',views.rent_records, name='rent_records'),
    path('book_cha',views.book_cha, name='book_cha'),
    path('validate_card',views.validate_card, name='validate_card'),
    path('validate_card2',views.validate_card2, name='validate_card2'),
    path('book_apa',views.book_apa, name='book_apa'),
    path('print_card/<int:id>',views.print_card, name='print_card'),
    path('check_people/', views.check_people, name='check_people'),
    path('entering_people/<int:booking_id>/', views.entering_people, name='entering_people'),
    path('save_person/', views.save_person, name='save_person'),
    path('settings', views.settings, name='settings'),
    path('mor', views.mor, name='mor'),

]